# Generated by Django 3.2 on 2021-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_discussion_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('file', models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(default='profile.PNG', upload_to='images/profile_pics/'),
        ),
    ]
