# Generated by Django 3.2 on 2021-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0008_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
