# Generated by Django 3.2 on 2021-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0011_remove_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='filename',
            field=models.TextField(max_length=500),
        ),
    ]
